// ONS Annual Survey of Hours and Earnings (ASHE), Table 14: gross annual pay by
// 4-digit SOC 2020 occupation, UK. Generated by scripts/ashe/build.mjs from the
// ONS files; do not edit ashe-data.json by hand.
//
// Figures are exactly as published by ONS. Cells ONS suppressed or left empty are
// null, with the ONS marker kept in `flags`. Nothing is estimated or filled in.
//
// Import this module from server components or route handlers only: the JSON is
// about 480 KB and should not be shipped to the browser.

import raw from "./ashe-data.json";

export type AsheBasis = "ft" | "all";

export type AsheField =
  | "jobsThousands"
  | "median"
  | "medianChangePct"
  | "mean"
  | "meanChangePct"
  | "p10"
  | "p20"
  | "p25"
  | "p30"
  | "p40"
  | "p60"
  | "p70"
  | "p75"
  | "p80"
  | "p90";

export type AsheLevelField = Exclude<AsheField, "medianChangePct" | "meanChangePct">;

/** ONS marker for a cell with no figure: x (CV over 20%), .. (disclosive), : (not applicable), - (nil), or blank. */
export type AsheMarker = "x" | ".." | ":" | "-" | "." | "blank";

export type AsheFigures = Record<AsheField, number | null> & {
  /** Coefficient of variation (%) from Table 14.7b for each level field. */
  cv: Record<AsheLevelField, number | null>;
  /** Present only when at least one cell had no figure. */
  flags?: Partial<Record<AsheField, AsheMarker>>;
};

export interface AsheUnitGroup {
  /** Official SOC 2020 unit group title (from SOC 2020 Volume 1). */
  title: string;
  /** The label ONS printed in the ASHE table, when worded differently from the SOC title. */
  asheLabel?: string;
  /** Full-time employee jobs. */
  ft: AsheFigures;
  /** All employee jobs (full-time and part-time). */
  all: AsheFigures;
}

export interface AsheGroup {
  title: string;
  level: "major" | "subMajor" | "minor";
  ft: AsheFigures;
  all: AsheFigures;
}

export interface AsheSource {
  publisher: string;
  survey: string;
  dataset: string;
  table: string;
  cvTable: string;
  measure: string;
  year: number;
  edition: "provisional" | "revised";
  /** ISO date the edition was first published by ONS. */
  releaseDate: string;
  correction: { date: string; note: string } | null;
  classification: string;
  geography: string;
  annualReferencePeriod: string;
  tableFootnoteA: string | null;
  tableFootnoteB: string | null;
  onsNotes: {
    coverage: string;
    annualPeriod: string;
    sample: string;
    suppression: string;
    jobCounts: string;
  };
  tableTitles: { ft: string; all: string };
  datasetUrl: string;
  fileUrl: string;
  zipSha256: string;
  retrievedAt: string;
  licence: { name: string; url: string };
  attribution: string;
  markers: Record<AsheMarker, string>;
  qualityKey: { maxCv: number; label: string }[];
}

export interface AsheDataset {
  source: AsheSource;
  national: { ft: AsheFigures; all: AsheFigures };
  groups: Record<string, AsheGroup>;
  unitGroups: Record<string, AsheUnitGroup>;
}

const DATA = raw as unknown as AsheDataset;

/** Provenance for every figure in this module. */
export const SOURCE: AsheSource = DATA.source;

/** UK figures for all employees in the table (the "All employees" row). */
export const ASHE_NATIONAL = DATA.national;

export const ASHE_UNIT_GROUPS: Readonly<Record<string, AsheUnitGroup>> = DATA.unitGroups;

/** SOC 2020 major, sub-major and minor groups (1 to 3 digits). */
export const ASHE_GROUPS: Readonly<Record<string, AsheGroup>> = DATA.groups;

export function getAsheUnitGroup(soc: string): AsheUnitGroup | undefined {
  return DATA.unitGroups[soc];
}

export function getAsheFigures(soc: string, basis: AsheBasis = "ft"): AsheFigures | undefined {
  return DATA.unitGroups[soc]?.[basis];
}

export function listSocCodes(): string[] {
  return Object.keys(DATA.unitGroups);
}

/**
 * ONS quality band for a coefficient of variation, using the key printed on the
 * ONS tables: up to 5% precise, up to 10% reasonably precise, up to 20% acceptable.
 * ONS does not publish estimates above 20%, so a null CV returns null.
 */
export function cvQuality(cv: number | null): "precise" | "reasonably precise" | "acceptable" | "unreliable" | null {
  if (cv === null) return null;
  if (cv <= 5) return "precise";
  if (cv <= 10) return "reasonably precise";
  if (cv <= 20) return "acceptable";
  return "unreliable";
}

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

function longDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return `${d} ${MONTHS[m - 1]} ${y}`;
}

/** e.g. "Source: ONS ASHE 2025 (provisional), Table 14.7a, published 23 October 2025" */
export function sourceLine(): string {
  return `Source: ONS ASHE ${SOURCE.year} (${SOURCE.edition}), Table ${SOURCE.table}, published ${longDate(SOURCE.releaseDate)}`;
}

/** Short form for tables and chart captions, e.g. "ONS ASHE 2025, Table 14.7a". */
export function sourceShort(): string {
  return `ONS ASHE ${SOURCE.year}, Table ${SOURCE.table}`;
}
