// ONS SOC 2020 Volume 1: official unit group titles, group descriptions, ONS
// "typical entry routes and associated qualifications" text and related job titles.
// Generated by scripts/ashe/build.mjs; do not edit soc2020.json by hand.
//
// Contains public sector information licensed under the Open Government Licence v3.0.
// If a page quotes `description` or `entryRoutes`, it must show SOC_SOURCE.attribution.
// Server-side use only (about 300 KB).

import raw from "./soc2020.json";

export interface SocUnitGroup {
  title: string;
  description: string;
  entryRoutes: string;
  relatedJobTitles: string[];
}

export interface SocSource {
  title: string;
  publisher: string;
  pageUrl: string;
  fileUrl: string;
  fileVersion: string;
  sha256: string;
  retrievedAt: string;
  licence: { name: string; url: string };
  attribution: string;
}

interface SocDataset {
  source: SocSource;
  groups: Record<string, { title: string; level: "major" | "subMajor" | "minor" }>;
  unitGroups: Record<string, SocUnitGroup>;
}

const DATA = raw as unknown as SocDataset;

export const SOC_SOURCE: SocSource = DATA.source;

export function getSocUnitGroup(soc: string): SocUnitGroup | undefined {
  return DATA.unitGroups[soc];
}

export function getSocGroupTitle(code: string): string | undefined {
  return DATA.groups[code]?.title ?? DATA.unitGroups[code]?.title;
}
