import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
      <div className="prose prose-gray max-w-none text-gray-600 space-y-4">
        <p>Last updated: April 2026</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">1. Service Description</h2>
        <p>MatchMySkillset provides AI-powered career matching and job discovery services. We analyse skills from your experience and match them to career opportunities and job listings.</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">2. Use of Service</h2>
        <p>You may use our free skills assessment tool without creating an account. To save results and access additional features, you must register with a valid email address.</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">3. AI-Generated Content</h2>
        <p>Career suggestions and skills analysis are generated by artificial intelligence and should be used as guidance, not definitive career advice. We recommend consulting with a career professional for major career decisions.</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">4. Job Listings</h2>
        <p>Job listings are sourced from third-party providers (Adzuna, Reed, Jooble) and employer submissions. We do not guarantee the accuracy of job listing information. Clicking on a job listing will take you to the original source where the listing was posted.</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">5. Acceptable Use</h2>
        <p>You agree not to: submit false or misleading information, use automated tools to access our service, attempt to reverse-engineer our matching algorithms, or use the service for any unlawful purpose.</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">6. Intellectual Property</h2>
        <p>The matching algorithms, skills taxonomy, and platform design are the intellectual property of MatchMySkillset. You retain ownership of any personal content you submit.</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">7. Limitation of Liability</h2>
        <p>MatchMySkillset provides career guidance tools on an &quot;as is&quot; basis. We are not liable for career decisions made based on our suggestions, job listing accuracy, or any losses arising from use of the service.</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">8. Changes to Terms</h2>
        <p>We may update these terms from time to time. Continued use of the service constitutes acceptance of any changes.</p>

        <h2 className="text-xl font-semibold text-gray-900 mt-8">9. Contact</h2>
        <p>For any queries about these terms, contact us at hello@matchmyskillset.com.</p>
      </div>
    </div>
  );
}
